[project]
name = "facial-expression-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepface>=0.0.100",
    "lap>=0.5.13",
    "mediapipe>=1.0.0",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "tf-keras>=2.21.0",
    "transformers>=5.15.0",
    "ultralytics>=8.4.118",
]
